// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA282eN3lEADxB2cStkHmFRo_LHrAVUrlU',
    appId: '1:819203212144:web:fa0f27aa2ee5d4adacc5b5',
    messagingSenderId: '819203212144',
    projectId: 'todo-app-e6a40',
    authDomain: 'todo-app-e6a40.firebaseapp.com',
    storageBucket: 'todo-app-e6a40.appspot.com',
    measurementId: 'G-VCNHEWKD59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqeOoArc_MmAO35GixjfYJJNU5VtxpBmM',
    appId: '1:819203212144:android:cfa5ed0eed514c64acc5b5',
    messagingSenderId: '819203212144',
    projectId: 'todo-app-e6a40',
    storageBucket: 'todo-app-e6a40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDedPUPiV7lr7MNUZ_3oJUxJT_I26GIiZI',
    appId: '1:819203212144:ios:b5fc79eed8e9c9f3acc5b5',
    messagingSenderId: '819203212144',
    projectId: 'todo-app-e6a40',
    storageBucket: 'todo-app-e6a40.appspot.com',
    iosClientId: '819203212144-kefttotuh5c5437r5poeblg64aoenqvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDedPUPiV7lr7MNUZ_3oJUxJT_I26GIiZI',
    appId: '1:819203212144:ios:b5fc79eed8e9c9f3acc5b5',
    messagingSenderId: '819203212144',
    projectId: 'todo-app-e6a40',
    storageBucket: 'todo-app-e6a40.appspot.com',
    iosClientId: '819203212144-kefttotuh5c5437r5poeblg64aoenqvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
